apiVersion: v1
kind: Service
metadata:
  name: {{ include "envio-indexer.fullname" . }}-hasura
  labels:
    {{- include "envio-indexer.labels" . | nindent 4 }}
    app.kubernetes.io/component: hasura
  {{- with .Values.hasura.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.hasura.service.type }}
  ports:
    - port: {{ .Values.hasura.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "envio-indexer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: hasura
