{{- if .Values.autoscaling.hasura.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "envio-indexer.fullname" . }}-hasura
  labels:
    {{- include "envio-indexer.labels" . | nindent 4 }}
    app.kubernetes.io/component: hasura
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "envio-indexer.fullname" . }}-hasura
  minReplicas: {{ .Values.autoscaling.hasura.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.hasura.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.hasura.targetCPUUtilizationPercentage }}
{{- end }}
