{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "envio-indexer.fullname" . }}
  labels:
    {{- include "envio-indexer.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "envio-indexer.fullname" $ }}-{{ default "hasura" .service }}
                port:
                  number: {{ ternary $.Values.indexer.service.port $.Values.hasura.service.port (eq (default "hasura" .service) "indexer") }}
          {{- end }}
    {{- end }}
{{- end }}
